development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: plan_your_ce_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: plan_your_ce_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: plan_your_ce
  pool: 5

cucumber:
  <<: *test
